### ISSUE TITLE
CP-TRB-03 - Registrar usuario existente

### ISSUE THREAD

**Issue by camiherrerap** [johnlopez796/tribuna_90#1]
El sistema permite la creación de usuarios con los mismos datos
DATOS DE PRUEBAS:
Tipo de documento: CC
Documento: 1010134032
Nombres:  Camila 
Apellidos: Herrera
Fecha de nacimiento: Dia: 14, Mes: Abril, Año: 1991
Email: camila@correo.com
Usuario: CamiH
Contraseña: 123-Adm1!n 
Repita la contraseña: 123-Adm1!n

**Comment by johnlopez796** [comment]
Se realizo la verificación desde el Back donde se determino que no existia la validación de usuarios existentes, por lo que se corrigio el error y se procedio a desplegar.

Se encuentra funcionando correctamente.
