### ISSUE TITLE
 CP-TRB-05 - Registrar usuario sin campos obligatorios

### ISSUE THREAD

**Issue by camiherrerap** [johnlopez796/tribuna_90#2]
El sistema permite registrar usuarios sin que se diligencien todos los campos obligatorios del formulario
DATOS DE PRUEBA
Documento: 1010134034
Nombres:  Maria
Email: camila@correo.com
Usuario: CamiHerrera
Contraseña: 123-Adm1!n

**Comment by johnlopez796** [comment]
Se realizo cambio en el TypeScript ya que las validaciones tenian problemas con los nombres, se corrigio y se verifico la funcionalidad.

Verificar y cerrar issue
