### ISSUE TITLE
CP-TRB-10 - Autenticación de usuario exitosa

### ISSUE THREAD

**Issue by camiherrerap** [johnlopez796/tribuna_90#3]
El sistema no permite iniciar sesión con un usuario recien registrado. 
Usuario: CamiH
Contraseña: 123-Adm1!n

**Comment by johnlopez796** [comment]
Se realizo la verificación sobre el registro de la plataforma y se identifico que uno de los campos no estaba llegando de manera correcta a la BD, por lo que se realizaron cambios en el Back para poder identificar y solucionar.

Ya se encuentra funcionando correctamente.
